# Generated by Django 3.2.5 on 2022-01-18 21:17

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_record_voice_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='voice_record',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='records'),
        ),
    ]
